services:
    db:
      container_name: postgres
      restart: always
      image: postgres
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: mirabel
      volumes:
        - postgres-data:/var/lib/postgresql/data

    webdriver:
        container_name: webdriver
        image: instrumentisto/geckodriver
        command: "--host=0.0.0.0 --allow-hosts=localhost --binary=/opt/firefox/firefox"
        ports:
          - 4444:4444

volumes:
  surrealdb-data:
  postgres-data:
