services:
    init-data:
        container_name: init
        image: busybox
        command: chmod -R 777 /data
        volumes:
          - surrealdb-data:/data

    surrealdb:
        container_name: surrealdb
        depends_on:
          - init-data
        env_file:
          - .env
        entrypoint:
          - /surreal
          - start
          - --user
          - $DB_USER
          - --pass
          - $DB_PASSWORD
          - rocksdb:/data/finanalize.db
        image: surrealdb/surrealdb:v2.1.4
        ports:
          - 8000:8000
        volumes:
          - surrealdb-data:/data

volumes:
  surrealdb-data:
