[package]
name = "mirabel-backend-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.8.0"
quote = { version = "1.0.40", features = ["proc-macro"] }
syn = { version = "1.0.109", features = ["extra-traits", "full"] }
